### ISSUE TITLE
How many results Sightings observe.observables can return ?

### ISSUE THREAD

**Issue by Link009** [CiscoSecurity/tr-05-api-module#95]
Hi

I am using Observe SMA Endpoint more or less successfully by now.
This is the function I am working on:

```
def cisco_sightings(value, client, inspect_response):
    artifact_type = inspect_response[0]["type"]

    response = client.enrich.observe.observables([{'type': artifact_type, 'value': value}])

    time.sleep(1)
    master_response["cisco_sightings"] = response
    return json.dumps(response, indent=4)
```

However I noted that the max result I have inside response variable is 100 elements. 
[SMA Max count Screenshot](https://i.imgur.com/WdBsol2.png)

How can I retrieve all of them, which for my input value, is way more than 100 ? How many results does observe.observables can return ? Is there any parameter to expand to more than a 100 ?

Thanks

**Comment by oshynk** [comment]
Hi. observe.observables can return 100 Sightings, there is no option to return them all. You can check [observe api](https://visibility.amp.cisco.com/iroh/iroh-enrich/index.html#/Observe/post_iroh_iroh_enrich_observe_observables) - there are no other parameters apart observable.

**Why such limitation is needed:** to prevent any misbehaving module from flooding the investigation.
**Why only 100 sightings:** the graph only supports 200 nodes. 100 is safe threshold to display sightings and their associated details.

I hope the question was answered. We are going to close this issue.
